services:
  mysql:
    container_name: mysql
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=superuser
    volumes:
      - data_mysql:/var/lib/mysql

volumes:
  data_mysql: